Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "precise32.box"
  
  #config.vm.share_folder "bootstrap", "/mnt/bootstrap", ".", :create => true
  config.vm.provision :shell, :path => "postgresql.sh"
  
  # PostgreSQL Server port forwarding
config.vm.network :forwarded_port, guest: 5432, host: 5432
end
